ALTER TABLE etapa_rastreamento
    MODIFY tipo ENUM(
        'NA_CHINA','AEROPORTO_ORIGEM','EM_TRANSITO','AEROPORTO_DESTINO',
        'NO_BRASIL','TAXA','CD_BRASIL','SAIDA_ENTREGA','ENTREGUE','DEVOLVIDO'
    ) NOT NULL;
